name: peers_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  file_picker: ^10.3.2
  url_launcher: ^6.3.1
  firebase_storage: ^13.0.0
  table_calendar: ^3.0.9
  firebase_app_check: ^0.4.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - .env
