// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_VKT4VX8PKpXUb85nSs_H0FyI0A2X28',
    appId: '1:106608947635:web:d688ea3ad090d117a01bc6',
    messagingSenderId: '106608947635',
    projectId: 'peer-app-88a0e',
    authDomain: 'peer-app-88a0e.firebaseapp.com',
    storageBucket: 'peer-app-88a0e.firebasestorage.app',
    measurementId: 'G-LHY22L41F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlMN-CRS-ddHIvr-Y-WwlmGO9k-NJw3g',
    appId: '1:106608947635:android:384f9b4f7de8a5c8a01bc6',
    messagingSenderId: '106608947635',
    projectId: 'peer-app-88a0e',
    storageBucket: 'peer-app-88a0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bVvtDVeAiFtQwP3k04P7xxqtMmMEnvE',
    appId: '1:106608947635:ios:035809b8d66bf9eba01bc6',
    messagingSenderId: '106608947635',
    projectId: 'peer-app-88a0e',
    storageBucket: 'peer-app-88a0e.firebasestorage.app',
    iosBundleId: 'com.example.peersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6bVvtDVeAiFtQwP3k04P7xxqtMmMEnvE',
    appId: '1:106608947635:ios:035809b8d66bf9eba01bc6',
    messagingSenderId: '106608947635',
    projectId: 'peer-app-88a0e',
    storageBucket: 'peer-app-88a0e.firebasestorage.app',
    iosBundleId: 'com.example.peersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl_VKT4VX8PKpXUb85nSs_H0FyI0A2X28',
    appId: '1:106608947635:web:19402b2fae708cdea01bc6',
    messagingSenderId: '106608947635',
    projectId: 'peer-app-88a0e',
    authDomain: 'peer-app-88a0e.firebaseapp.com',
    storageBucket: 'peer-app-88a0e.firebasestorage.app',
    measurementId: 'G-ZBN110454Y',
  );
}
